# Generated by Django 4.1.5 on 2023-01-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markers',
            name='group',
            field=models.CharField(choices=[('parks_and_museums', 'parks_and_museums'), ('attractions', 'attractions')], default='attractions', max_length=20),
        ),
    ]
