# Generated by Django 4.1.5 on 2023-01-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_markers_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markers',
            name='group',
            field=models.CharField(choices=[('parks_and_museums', 'Парки и музеи'), ('attractions', 'Достопримечательности')], default='attractions', max_length=20),
        ),
    ]
